In [1]:
import pandas as pd
import json
from pprint import pprint
from item.historical.scripts.util.managers.dataframe import DataframeManager
from item.historical.scripts.util.managers.dataframe import ColumnName
from item.historical.scripts.util.managers.country_code import CountryCodeManager
from item.common import paths

# Variables used across the notebook and not changed

In [2]:
DATASET_ID = "T005"
dataframeManager = DataframeManager(DATASET_ID)
countryCodeManager = CountryCodeManager()

# Opening the dataset

In [3]:
path = paths['data']/'historical'/'input'/'T005_input.csv'
df = pd.read_csv(path)
df

,IPCC-Annex,World Region,ISO_A3,Name,IPCC,IPCC_description,1970,1971,1972,1973,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Annex_I,Canada,CAN,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Annex_I,Canada,CAN,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Annex_I,Canada,CAN,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Annex_I,Canada,CAN,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Annex_I,Canada,CAN,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Non-Annex_I,Oceania,WSM,Samoa,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Non-Annex_I,Oceania,WSM,Samoa,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Non-Annex_I,Oceania,WSM,Samoa,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Int. Shipping,Int. Shipping,SEA,Int. Shipping,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Int. Aviation,Int. Aviation,AIR,Int. Aviation,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Dropping Unnecessary columns
    Rule: To comply with the latest template, we will drop all the unnecessary columns and rename others

In [4]:
df.drop(columns=["IPCC-Annex", "World Region", "ISO_A3"], inplace=True)
df

,Name,IPCC,IPCC_description,1970,1971,1972,1973,1974,1975,1976,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,50500.000000,54000.000000,58700.00000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,32700.000000,34000.000000,32400.00000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,100000.000000,90700.000000,90500.00000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,8020.000000,8300.000000,8170.00000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,81900.000000,85300.000000,90900.00000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Samoa,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,0.000039,0.000039,0.00002,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Samoa,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,0.007510,0.007570,0.00762,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Samoa,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,1.130000,1.160000,1.08000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Int. Shipping,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,366000.000000,341000.000000,352000.00000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Int. Aviation,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,180000.000000,174000.000000,174000.00000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Renaming "Name" column to "Country"
    Rule: Renaming to comply with the template.

In [5]:
dataframeManager.rename_column(current_name="Name",df=df,new_name=ColumnName.COUNTRY.value)
df

,Country,IPCC,IPCC_description,1970,1971,1972,1973,1974,1975,1976,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,50500.000000,54000.000000,58700.00000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,32700.000000,34000.000000,32400.00000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,100000.000000,90700.000000,90500.00000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,8020.000000,8300.000000,8170.00000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,81900.000000,85300.000000,90900.00000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Samoa,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,0.000039,0.000039,0.00002,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Samoa,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,0.007510,0.007570,0.00762,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Samoa,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,1.130000,1.160000,1.08000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Int. Shipping,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,366000.000000,341000.000000,352000.00000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Int. Aviation,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,180000.000000,174000.000000,174000.00000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

## Renaming two Countries
    Rule: The dataset has two countries that are not country names. This is how they will be mapped
        Original Name --> New Name
        Int. Aviation --> World
        Int. Shipping --> World
        
    Note: Int. Aviation is located at index 3361 and Int. Shipping at index 3362

In [6]:
df["Country"][3361] = "World"
df["Country"][3362] = "World"
df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Country,IPCC,IPCC_description,1970,1971,1972,1973,1974,1975,1976,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,50500.000000,54000.000000,58700.00000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,32700.000000,34000.000000,32400.00000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,100000.000000,90700.000000,90500.00000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,8020.000000,8300.000000,8170.00000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,81900.000000,85300.000000,90900.00000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Samoa,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,0.000039,0.000039,0.00002,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Samoa,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,0.007510,0.007570,0.00762,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Samoa,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,1.130000,1.160000,1.08000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,World,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,366000.000000,341000.000000,352000.00000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,World,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,180000.000000,174000.000000,174000.00000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Adding the "Source" columns
    Rule: This data set came from European Commission

In [7]:
dataframeManager.simple_column_insert(cell_value="Joint Research Center", dataframe=df, column_name= ColumnName.SOURCE.value)
df

,Source,Country,IPCC,IPCC_description,1970,1971,1972,1973,1974,1975,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Joint Research Center,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,50500.000000,54000.000000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Joint Research Center,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,32700.000000,34000.000000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Joint Research Center,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,100000.000000,90700.000000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Joint Research Center,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,8020.000000,8300.000000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,81900.000000,85300.000000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Joint Research Center,Samoa,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,0.000039,0.000039,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Joint Research Center,Samoa,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,0.007510,0.007570,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Joint Research Center,Samoa,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,1.130000,1.160000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Joint Research Center,World,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,366000.000000,341000.000000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,180000.000000,174000.000000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Getting the ISO Code for each country
    Rule: For each country we need to assign its ISO code

## Determining which countries do not have an ISO code
    Rule: As shown below, various countries do not have an ISO Code, this is the mapping done for each country to obtain their ISO code or the ISO code that will be used for each country
        ORIGINAL NAME ----> NEW NAME/ISO Code
    > Serbia and Montenegro --> SCG
    
    > Swaziland --> Eswatini
    
    > World --> WLD (we will use this code)
    
    > Saint Helena --> Saint Helena, Ascension and Tristan da Cunha
    
    > Macedonia, the former Yugoslav Republic of --> ?
    
    > Libyan Arab Jamahiriya --> Libya
    
    > Congo_the Democratic Republic of the --> Congo, The Democratic Republic of the
    
    > Reunion --> Réunion
    
    > Virgin Islands_British --> Virgin Islands, British
    
    > Cote d'Ivoire --> Côte d'Ivoire
    
    > Netherlands Antilles --> ANT
    
    > Taiwan_Province of China --> Taiwan, Province of China
    
    > Cape Verde --> Cabo Verde
    
    > Tanzania_United Republic of --> Tanzania, United Republic of

In [8]:
list_of_countries = list(set(df["Country"]))
countries_with_no_iso_code = countryCodeManager.get_list_of_countries_with_no_iso_code(list_of_countries)
countries_with_no_iso_code

['Serbia and Montenegro',
 'World',
 'Saint Helena',
 'Tanzania_United Republic of',
 'Cape Verde',
 "Cote d'Ivoire",
 'Libyan Arab Jamahiriya',
 'Netherlands Antilles',
 'Swaziland',
 'Macedonia, the former Yugoslav Republic of',
 'Reunion',
 'Virgin Islands_British',
 'Congo_the Democratic Republic of the',
 'Taiwan_Province of China']

## Cleaning the list of countries to obtain their ISO Code

In [9]:
country_column = list(df[ColumnName.COUNTRY.value])
list_of_iso_code = []


for country in country_column:
    if country == "Serbia and Montenegro":
        code = "SCG"
        
    elif country == "Swaziland":
        code = countryCodeManager.get_iso_code_for_country("Eswatini")
        
    elif country == "World":
        code = "WLD"
        
    elif country == "Saint Helena":
        code = countryCodeManager.get_iso_code_for_country("Saint Helena, Ascension and Tristan da Cunha")
        
    elif country == "Macedonia, the former Yugoslav Republic of":
        #Problem
        code = countryCodeManager.get_iso_code_for_country("Macedonia, the former Yugoslav Republic of")
        
    elif country == "Libyan Arab Jamahiriya":
        code = countryCodeManager.get_iso_code_for_country("Libya")
        
    elif country == "Congo_the Democratic Republic of the":
        code = countryCodeManager.get_iso_code_for_country("Congo, The Democratic Republic of the")
        
    elif country == "Reunion":
        code = countryCodeManager.get_iso_code_for_country("Réunion")
        
    elif country == "Virgin Islands_British":
        code = countryCodeManager.get_iso_code_for_country("Virgin Islands, British")
        
    elif country == "Cote d'Ivoire":
        code = countryCodeManager.get_iso_code_for_country("Côte d'Ivoire")
                                         
    elif country == "Netherlands Antilles":
        code = "ANT"
                                         
    elif country == "Taiwan_Province of China":
        code = countryCodeManager.get_iso_code_for_country("Taiwan, Province of China")
                                         
    elif country == "Cape Verde":
        code = countryCodeManager.get_iso_code_for_country("Cabo Verde")
                                         
    elif country == "Tanzania_United Republic of":
        code = countryCodeManager.get_iso_code_for_country("Tanzania, United Republic of") 
        
    else:
        code = countryCodeManager.get_iso_code_for_country(country)
    
    # Appending the code
    list_of_iso_code.append(code)
        
# Assert that the size of the list of iso codes is equivalent to the size of country column
assert len(list_of_iso_code) == len(country_column)


# Assert that all the iso codes are 3 characters long
for iso_code in list_of_iso_code:
    assert len(iso_code) == 3
    
# Adding the ISO column to the dataframe
df.insert(2, ColumnName.ISO_CODE.value, list_of_iso_code, True)
df

,Source,Country,ISO Code,IPCC,IPCC_description,1970,1971,1972,1973,1974,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Joint Research Center,Canada,CAN,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,50500.000000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Joint Research Center,Canada,CAN,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,32700.000000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Joint Research Center,Canada,CAN,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,100000.000000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Joint Research Center,Canada,CAN,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,8020.000000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,81900.000000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Joint Research Center,Samoa,WSM,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,0.000039,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Joint Research Center,Samoa,WSM,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,0.007510,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Joint Research Center,Samoa,WSM,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,1.130000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Joint Research Center,World,WLD,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,366000.000000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,180000.000000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Getting the ITEM code for each ISO region
    Rule: For each country we need to assign an ITEM region

## Determining which ISO codes do not have a region
    Rule: As seen from the cell below, all countries have an region associated to them except for the countries that we had problem defining their ISO code.

In [10]:
list_of_unique_iso_codes = list(set(df[ColumnName.ISO_CODE.value]))
iso_codes_with_no_region = countryCodeManager.get_list_of_iso_codes_with_no_region(list_of_unique_iso_codes)
iso_codes_with_no_region

['N/A', 'WLD']

##  Assigning the ITEM region column

In [11]:
# Getting the complete list of iso codes
list_of_all_codes = df[ColumnName.ISO_CODE.value]

# Getting the list of regions
item_regions = countryCodeManager.get_list_of_regions_for_iso_codes(list_of_all_codes)

# Hardcoding the region value for WLD ISO Code
for index in range(0, len(list_of_all_codes)):
    if list_of_all_codes[index] == "WLD":
        item_regions[index] = "World"

# Adding the column to the dataframe
df.insert(3, ColumnName.ITEM_REGION.value, item_regions, True)
df

,Source,Country,ISO Code,Region,IPCC,IPCC_description,1970,1971,1972,1973,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Joint Research Center,Canada,CAN,Canada,1.A.1.a,Main Activity Electricity and Heat Production,45000.00000,49300.00000,50100.00000,51900.000000,...,107000.00000,110000.0000,107000.00000,101000.00000,100896.528700,101494.798400,102929.457500,99422.722410,100415.874400,89066.181500
1,Joint Research Center,Canada,CAN,Canada,1.A.1.bc,Petroleum Refining - Manufacture of Solid Fuel...,29500.00000,30600.00000,32200.00000,34300.000000,...,96500.00000,100000.0000,101000.00000,110000.00000,116569.985400,117834.506100,117305.138200,123630.805000,126432.233500,131379.301800
2,Joint Research Center,Canada,CAN,Canada,1.A.2,Manufacturing Industries and Construction,78300.00000,77200.00000,79500.00000,96500.000000,...,58500.00000,61800.0000,66200.00000,67300.00000,65597.043900,64490.986900,62075.863900,63398.469410,64582.363050,63941.293950
3,Joint Research Center,Canada,CAN,Canada,1.A.3.a,Civil Aviation,5970.00000,6140.00000,6470.00000,7340.000000,...,10600.00000,9970.0000,10700.00000,13200.00000,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,1.A.3.b,Road Transportation,64300.00000,66700.00000,71500.00000,78300.000000,...,135000.00000,139000.0000,139000.00000,138000.00000,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3358,Joint Research Center,Samoa,WSM,Other Asia-Pacific,1.B.2,Oil and Natural Gas,0.00002,0.00002,0.00002,0.000039,...,0.08840,0.0763,0.07280,0.06830,0.056962,0.066701,0.080413,NaN,NaN,NaN
3359,Joint Research Center,Samoa,WSM,Other Asia-Pacific,2.A.3,Glass Production,0.00716,0.00727,0.00737,0.007440,...,0.00924,0.0093,0.00937,0.00945,0.009442,0.009519,0.009596,0.009655,0.009714,0.009774
3360,Joint Research Center,Samoa,WSM,Other Asia-Pacific,2.D,Non-Energy Products from Fuels and Solvent Use,1.05000,1.06000,1.09000,1.120000,...,1.34000,1.3200,1.32000,1.32000,1.302925,1.299835,1.296412,1.291261,1.286466,1.282006
3361,Joint Research Center,World,WLD,World,1.A.3.d,Water-borne Navigation,354000.00000,354000.00000,371000.00000,392000.000000,...,616000.00000,663000.0000,668000.00000,605000.00000,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,1.A.3.a,Civil Aviation,169000.00000,169000.00000,179000.00000,187000.000000,...,435000.00000,458000.0000,473000.00000,480000.00000,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Removing unnecessary rows
        Rule: This dataset contains information CO2 emissions, so we removed all kepts the rows that has an IPCC code of 1.A.3 and its sub categories (a to e)

In [12]:
# Removing the rows that are not useful
list_of_index_to_remove = []

# Finding the index to remove 
for index, row in df.iterrows():
    if row["IPCC"] not in ["1.A.3","1.A.3.a","1.A.3.b","1.A.3.c","1.A.3.d","1.A.3.e"]:
        list_of_index_to_remove.append(index)

# Removing the unwanted rows
df.drop(df.index[list_of_index_to_remove], inplace = True)
df

,Source,Country,ISO Code,Region,IPCC,IPCC_description,1970,1971,1972,1973,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,1.A.3.a,Civil Aviation,5970.000,6140.000,6470.000,7340.00,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,1.A.3.b,Road Transportation,64300.000,66700.000,71500.000,78300.00,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,1.A.3.c,Railways,6040.000,6400.000,6720.000,6850.00,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,1.A.3.d,Water-borne Navigation,4290.000,4500.000,5020.000,5310.00,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,1.A.3.e,Other Transportation,NaN,NaN,NaN,NaN,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,1.A.3.b,Road Transportation,12.900,12.900,13.600,13.30,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,1.A.3.d,Water-borne Navigation,0.461,0.461,0.534,0.51,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,1.A.3.e,Other Transportation,NaN,NaN,NaN,NaN,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,1.A.3.d,Water-borne Navigation,354000.000,354000.000,371000.000,392000.00,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,1.A.3.a,Civil Aviation,169000.000,169000.000,179000.000,187000.00,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Adding the 'Variable' and 'Unit' column
    Rule: The variable for the CO2 emissions is 'CO2 Emission (ttw)' and the unit is 10^6 t CO2 / yr

## Adding the 'Variable' column

In [13]:
dataframeManager.simple_column_insert(df, ColumnName.VARIABLE.value, "CO2 Emission (ttw)", 4)
df

,Source,Country,ISO Code,Region,Variable,IPCC,IPCC_description,1970,1971,1972,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),1.A.3.a,Civil Aviation,5970.000,6140.000,6470.000,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),1.A.3.b,Road Transportation,64300.000,66700.000,71500.000,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),1.A.3.c,Railways,6040.000,6400.000,6720.000,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),1.A.3.d,Water-borne Navigation,4290.000,4500.000,5020.000,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),1.A.3.e,Other Transportation,NaN,NaN,NaN,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),1.A.3.b,Road Transportation,12.900,12.900,13.600,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),1.A.3.d,Water-borne Navigation,0.461,0.461,0.534,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),1.A.3.e,Other Transportation,NaN,NaN,NaN,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),1.A.3.d,Water-borne Navigation,354000.000,354000.000,371000.000,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),1.A.3.a,Civil Aviation,169000.000,169000.000,179000.000,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

## Adding the 'Unit' column

In [14]:
dataframeManager.simple_column_insert(df, ColumnName.UNIT.value, '10^6 t CO2 / yr', 5)
df

,Source,Country,ISO Code,Region,Variable,Unit,IPCC,IPCC_description,1970,1971,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.a,Civil Aviation,5970.000,6140.000,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.b,Road Transportation,64300.000,66700.000,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.c,Railways,6040.000,6400.000,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.d,Water-borne Navigation,4290.000,4500.000,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.e,Other Transportation,NaN,NaN,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.b,Road Transportation,12.900,12.900,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.d,Water-borne Navigation,0.461,0.461,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.e,Other Transportation,NaN,NaN,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.d,Water-borne Navigation,354000.000,354000.000,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,1.A.3.a,Civil Aviation,169000.000,169000.000,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Adding the 'Service', 'Technology', 'Fuel', 'Vehicle Type' columns
    Rule: This dataset does not provide information regarding 'Technology', 'Fuel', or 'Vehicle Type.' Therefore, for both columns, the values is "All". Moreover, the data does not provide info about the type of service (e.g., if the data is about freight or passenger), therefore, 'Service' is also "All"

## Adding the "Technology" column

In [15]:
dataframeManager.simple_column_insert(df, ColumnName.TECHNOLOGY.value, "All", 6)
df

,Source,Country,ISO Code,Region,Variable,Unit,Technology,IPCC,IPCC_description,1970,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.a,Civil Aviation,5970.000,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.b,Road Transportation,64300.000,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.c,Railways,6040.000,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.d,Water-borne Navigation,4290.000,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.e,Other Transportation,NaN,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.b,Road Transportation,12.900,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.d,Water-borne Navigation,0.461,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.e,Other Transportation,NaN,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.d,Water-borne Navigation,354000.000,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,1.A.3.a,Civil Aviation,169000.000,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

## Adding the "Fuel" column

In [16]:
dataframeManager.simple_column_insert(df, ColumnName.FUEL.value, "All", 7)
df

,Source,Country,ISO Code,Region,Variable,Unit,Technology,Fuel,IPCC,IPCC_description,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.a,Civil Aviation,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.b,Road Transportation,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.c,Railways,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.d,Water-borne Navigation,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.e,Other Transportation,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.b,Road Transportation,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.d,Water-borne Navigation,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.e,Other Transportation,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.d,Water-borne Navigation,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,1.A.3.a,Civil Aviation,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

## Adding the 'Vechicle Type' column

In [17]:
dataframeManager.simple_column_insert(df, ColumnName.VEHICLE_TYPE.value, "All", 6)
df

,Source,Country,ISO Code,Region,Variable,Unit,Vehicle Type,Technology,Fuel,IPCC,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.a,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.b,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.c,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.d,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.e,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.b,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.d,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.e,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.d,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,1.A.3.a,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

## Adding the 'Service' column

In [18]:
dataframeManager.simple_column_insert(df, ColumnName.SERVICE.value, "All", 6)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Vehicle Type,Technology,Fuel,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,All,All,All,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Adding the 'Mode' column
    Rule: There are five IPCC descriptions and this is how each one is mapped to our schema:
        1. For countries:
            IPCC --> Mode
            Railways --> Rail
            Road Transportation --> Road
            Civil Aviation --> Air
            Other Transportation --> Other
            Water-borne Navigation --> Shipping
            
        2. For Int. Aviation country:
            IPCC --> Mode
            Civil Aviation --> Domestic Aviation
            
        3. For Int. Shipping country:
            IPCC --> Mode
            Water-Borne Navigation --> Domestic Shipping

In [19]:
mode_column = []

for index, row in df.iterrows():
    country = row["Country"]
    ipcc = row["IPCC_description"]
    
    if country == "Int. Aviation":
        mode_column.append("Domestic Aviation")
    elif country == "Int. Shipping":
        mode_column.append("Domestic Shipping")
    else:
        if ipcc == "Railways":
            mode_column.append("Rail")
        elif ipcc == "Road Transportation":
            mode_column.append("Road")
        elif ipcc == "Civil Aviation":
            mode_column.append("Air")
        elif ipcc == "Other Transportation":
            mode_column.append("Other")
        else:
            mode_column.append("Shipping")
            
# Assert the size of the mode column in the same as the size of the df
assert len(mode_column) == len(df)

# Adding the mode column to the df
df.insert(7, ColumnName.MODE.value, mode_column, True)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Road,All,All,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Rail,All,All,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Other,All,All,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Road,All,All,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Other,All,All,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Removing the IPCC_Description column

In [20]:
df.drop(columns=["IPCC_description", "IPCC"], inplace=True)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,...,10600.00,9970.00,10700.00,13200.00,14438.269950,14326.140000,14440.560000,14835.419060,14828.293890,14991.278770
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Road,All,All,...,135000.00,139000.00,139000.00,138000.00,141366.555000,140104.328500,140013.656200,138703.119800,138639.758100,140167.662000
5,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Rail,All,All,...,4590.00,5930.00,6790.00,6850.00,6594.230000,6761.550000,6698.420000,6881.579922,6878.274830,6953.877243
6,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,6150.00,6370.00,5300.00,5300.00,4835.830000,4449.770000,4008.830000,4118.446445,4116.468434,4161.714510
7,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Other,All,All,...,6860.00,6610.00,6470.00,6320.00,7187.638700,8556.488800,8662.548000,8874.857388,9183.152329,9672.816137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Road,All,All,...,42.70,52.20,74.00,136.00,126.688285,57.609525,54.533831,55.534452,57.013464,58.586162
3353,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,1.50,1.48,4.04,4.29,2.979700,4.878931,4.607964,4.607964,4.730685,4.861179
3354,Joint Research Center,Samoa,WSM,Other Asia-Pacific,CO2 Emission (ttw),10^6 t CO2 / yr,All,Other,All,All,...,1.99,2.44,3.27,3.59,2.865540,3.045044,2.877185,2.877185,2.953811,3.035291
3361,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Shipping,All,All,...,616000.00,663000.00,668000.00,605000.00,611213.371200,628002.812600,657324.001400,677043.721400,683814.158600,697490.441800
3362,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,...,435000.00,458000.00,473000.00,480000.00,490178.788900,504486.996300,529686.625500,553076.212300,559247.439500,564612.451700

# Transforming the dataframe in programming friendly view

In [21]:
all_data_frames = []
counter = 0
for index, row in df.iterrows():
    original_row = dict(row)
    list_of_year_value = []
    for column in list(original_row.keys()):
        if column.isdigit():
            list_of_year_value.append(column)
            del original_row[column]
    
    for year in list_of_year_value:
        newdict = original_row.copy()
        newdict[ColumnName.YEAR.value] = year
        newdict[ColumnName.VALUE.value] = row[year]
        local_df = pd.DataFrame(newdict, index = [counter])
        all_data_frames.append(local_df)
        counter = counter + 1

In [22]:
# Asserting that no info was missing. The 11 represents the default 11 non numeric columns from the schema of the UF view
assert len(all_data_frames) == ((df.shape[1] - 11) * df.shape[0])
df = pd.concat(all_data_frames)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,Fuel,Year,Value
0,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1970,5970.0000
1,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1971,6140.0000
2,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1972,6470.0000
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1973,7340.0000
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1974,8020.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37431,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2014,504486.9963
37432,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2015,529686.6255
37433,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2016,553076.2123
37434,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2017,559247.4395
37435,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2018,564612.4517

# Setting the correct magnitude for the "Value" column
    We will devide all values by 1000 in order to get the designed unit magnitude

In [23]:
# Variable holding the new magnitudes
new_magnitude_value = []

# For each value, convert them to billion
current_magnitude = df["Value"]
for value in current_magnitude:
    new_val = value/1000.0
    new_magnitude_value.append(new_val)
    
# Assert that the len of the new list is equal to the old list
assert len(new_magnitude_value) == len(current_magnitude)

# Remove the old "value" column
df.drop(columns= ["Value"],inplace = True)

# Add the new "Value" column
df[ColumnName.VALUE.value] = new_magnitude_value
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,Fuel,Year,Value
0,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1970,5.970000
1,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1971,6.140000
2,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1972,6.470000
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1973,7.340000
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,1974,8.020000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37431,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2014,504.486996
37432,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2015,529.686625
37433,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2016,553.076212
37434,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2017,559.247439
37435,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,2018,564.612452

# Reordering the columns
    Rule: To comply with the current template, the columns must be shown in a specific order. The dataframe manager specifies the order of the columns

In [24]:
df = dataframeManager.reorder_columns(df)
df

,Source,Country,ISO Code,Region,Variable,Unit,Service,Mode,Vehicle Type,Technology,Fuel,Value,Year
0,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,5.970000,1970
1,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,6.140000,1971
2,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,6.470000,1972
3,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,7.340000,1973
4,Joint Research Center,Canada,CAN,Canada,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,8.020000,1974
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37431,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,504.486996,2014
37432,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,529.686625,2015
37433,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,553.076212,2016
37434,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,559.247439,2017
37435,Joint Research Center,World,WLD,World,CO2 Emission (ttw),10^6 t CO2 / yr,All,Air,All,All,All,564.612452,2018

# Exporting Results

In [311]:
# Programming Friendly View
dataframeManager.create_programming_friendly_file(df)

# User Friendly View
dataframeManager.create_user_friendly_file(df)

> PF File saved at: /Users/hlinero/Documents/database/item/historical/scripts
> UF File saved at: /Users/hlinero/Documents/database/item/historical/scripts